services:
  mindlab-mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    container_name: mindlab-golang-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - api.network

  mindlab-golang:
    build:
      context: .
      dockerfile: build/Dockerfile
      target: dev # dev
#      target: runtime #prod
    container_name: mindlab-golang
    working_dir: /var/www/mindlab
#    command: ["go", "run", "./cmd/app/main.go"] # dev rebuild
    command: "tail -f /dev/null" # dev active
#    command: ['/app/app'] #prod
    ports:
      - "8009:8009"
    volumes:
      - ./:/var/www/mindlab  # dev
    env_file:
      - ./build/.env
    depends_on:
      - mindlab-mongodb
    networks:
      - api.network

networks:
  api.network:
